[package]
name = "clearlist"
version = "0.1.5"
edition = "2021"
license = "MIT"
default-run = "clearlist"
[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }
[dependencies]
serde_json = "1"
tauri = { version = "2.11.5", features = [] }
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
clearlist-core = { path = "../crates/core" }
[features]
custom-protocol = ["tauri/custom-protocol"]
